### ISSUE TITLE
Why cot not supported for Mathverse

### ISSUE THREAD

**Issue by huiyeruzhou** [EvolvingLMMs-Lab/lmms-eval#104]
Hi! I'm looking the evaluation config of mathverse in `lmms-eval/lmms_eval/tasks/mathverse/mathverse_testmini.yaml` 

```yaml
model_specific_prompt_kwargs:
  default:
    shot_type: "format-prompt" # can also be "custom-prompt"
    query_type: "query_wo" # now only support query_wo
```
What will happen if query_type is specified as ”query_cot"? When I read `MathVerseEvaluator.create_one_query`, it seems that change `query_type` will just change the input prompt.

```python
        # question
        if shot_type == "format-prompt":
            question_text = f"{problem[query_type]}"
```

I guess that maybe the difficulty is to implement the evaluation strategy for cot? Thanks for any helpful comment.
