### ISSUE TITLE
[FAQ] about caching the zipped file from HF to local folder

### ISSUE THREAD

**Issue by Luodian** [EvolvingLMMs-Lab/lmms-eval#124]
If you encountered connection issue when downloading the video zipped files to your local cache dir, please consider adding the following kwargs to your yaml file to forcefully download and zip the videos correctly to your local folder.

For example,

```yaml
# lmms_eval/tasks/videomme/videomme.yaml
dataset_kwargs:
  token: True
  cache_dir: videomme
  video: True
  force_download: True
  force_unzip: True
```
